### ISSUE TITLE
Deploy not working on kubernetes 1.5

### ISSUE THREAD

**Issue by roffe** [gluster/gluster-kubernetes#145]
Updated topology.json to include my nodes, when i try to deploy i get:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
➜  deploy git:(master) ✗ ./gk-deploy -g
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Add the 'heketi-service-account' Service Account to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
Using OpenShift CLI.
NAME          STATUS    AGE
kube-system   Active    7d
Using namespace "kube-system".
error: error validating "./ocp-templates/deploy-heketi-template.yaml": error validating data: couldn't find type: v1.Template; if you choose to ignore these errors, turn validation off with --validate=false
Error from server (AlreadyExists): error when creating "./ocp-templates/heketi-service-account.yaml": serviceaccounts "heketi-service-account" already exists
error: error validating "./ocp-templates/heketi-template.yaml": error validating data: couldn't find type: v1.Template; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "./ocp-templates/glusterfs-template.yaml": error validating data: couldn't find type: v1.Template; if you choose to ignore these errors, turn validation off with --validate=false
Error: unknown command "policy" for "kubectl"
Run 'kubectl --help' for usage.
node "10.50.41.201" labeled
node "10.50.41.202" labeled
node "10.50.41.203" labeled
Error: unknown command "process" for "kubectl"
Run 'kubectl --help' for usage.
error: no objects passed to create
Waiting for GlusterFS pods to start ... Timed out waiting for pods matching 'glusterfs-node=pod'.
No resources found
the server doesn't have a resource type "dc"
Error from server (NotFound): services "heketi-storage-endpoints" not found
serviceaccount "heketi-service-account" deleted
the server doesn't have a resource type "template"
the server doesn't have a resource type "template"
node "10.50.41.201" labeled
node "10.50.41.202" labeled
node "10.50.41.203" labeled
No resources found
the server doesn't have a resource type "template"
```

**Comment by jarrpa** [comment]
The problem seems to arise at `Using OpenShift CLI.`. It is detecting the `oc` command and not `kubectl`. Can you post the output to the following two commands?

```
type kubectl
type oc
```

**Comment by roffe** [comment]
Hi jarrpa

```
> ➜  ~ type kubectl
> kubectl is /usr/local/bin/kubectl
> ➜  ~ type oc
> oc not found
```

**Comment by roffe** [comment]
Hi again

I managed to get alittle further by forcing cli to kubectl.

Still getting strange problems thought:

```
➜  deploy git:(master) ✗ ./gk-deploy -g -c kubectl
expr: syntax error
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Add the 'heketi-service-account' Service Account to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
Using Kubernetes CLI.
NAME          STATUS    AGE
kube-system   Active    8d
Using namespace "kube-system".
serviceaccount "heketi-service-account" created
node "10.50.41.201" labeled
node "10.50.41.202" labeled
node "10.50.41.203" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Failed to communicate with deploy-heketi service.
service "deploy-heketi" deleted
deployment "deploy-heketi" deleted
the server doesn't have a resource type "dc"
Error from server (NotFound): services "heketi-storage-endpoints" not found
serviceaccount "heketi-service-account" deleted
node "10.50.41.201" labeled
node "10.50.41.202" labeled
node "10.50.41.203" labeled
```

**Comment by roffe** [comment]
More updates:

After having to adhoc the deploy script to insert a pause so i have a chance to establish a port-forward from my laptop into the heketi pod so it can communicate i'm now down to these errors:

jk@ratch-linux:~/gluster-kubernetes/deploy$ ./gk-deploy -g -c kubectl
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Add the 'heketi-service-account' Service Account to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
Using Kubernetes CLI.
NAME          STATUS    AGE
kube-system   Active    8d
Using namespace "kube-system".
serviceaccount "heketi-service-account" created
node "10.50.41.201" labeled
node "10.50.41.202" labeled
node "10.50.41.203" labeled
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Press SPACE to continue or Ctrl+C to exit ...
Continuing ...
Creating cluster ... ID: 397f545934956b7194d8a4faa342a67c
	Creating node 10.50.41.201 ... ID: 0072f8fd7ddb15aca4de4314ac7ba6bd
		Adding device /dev/sdb ... OK
	Creating node 10.50.41.202 ... ID: bee7bf1e6166eae6b4a4a9afda141f97
		Adding device /dev/sdb ... OK
	Creating node 10.50.41.203 ... ID: 9291d5400216a998bb88cb77225d3b44
		Adding device /dev/sdb ... OK
Error: Unable to execute command on glusterfs-ktqdn:   /usr/sbin/modprobe failed: 1
  Cannot read thin-pool target version.
  thin: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
Failed on setup openshift heketi storage

The kubernetes hosts are running CoreOS 1185.3.0 with 4.7.3-coreos-r2 kernel

**Comment by roffe** [comment]
Solved with https://github.com/gluster/gluster-kubernetes/issues/19

`modprobe dm_thin_pool` on nodes

**Comment by roffe** [comment]
I had to insert a "press space to continue" before it checks the heketi service where i established a kubectl port-forward to the heketi pod on port 8080, elsewise nothing would work from my work laptop that does not run kube-proxy

**Comment by jarrpa** [comment]
Okay, cool. So I'm seeing you've uncovered three things:

 1. Not propertly detecting kubectl
 2. I see an expr syntax error in your output
 3. A need to do a `modprobe` on all nodes.

I can't seem to replicate 1. If you'd be willing to help me troubleshoot that one I'd appreciate the help. Could you insert the following around https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L322:
```
echo $CLI
```
And then this after https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L351:
```
echo $CLI
exit 1
```
And see what we get?

For issue 2, I see a typo in the code I can easily fix.

For issue 3, would an update to the requirements documentation stating the `dm_thin_pool` module should be loaded be sufficient?

**Comment by roffe** [comment]
Hi jarrpa

1.  I added "CLI#:" to the echo to distinct them as the first one seems to return empty on my mac

Output:

```
➜  deploy git:(master) ✗ ./gk-deploy -g
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Add the 'heketi-service-account' Service Account to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
CLI1:
CLI2:  /usr/local/bin/kubectl
```

2. Super

3. Yes, that should be sufficient

**Comment by jarrpa** [comment]
I'll get to work on 2 and 3 soon.

As for 1.... that's odd. Can you move the `exit 1` to https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L360 and see if, without your changes, you're still getting the `Using OpenShift CLI.`?

**Comment by roffe** [comment]
Hi again.

Yes, if i don't specify `-c kubectl` it still defaults to OC cli

Added a third echo and moved the exit 1 down to #360

Result:

```
➜  deploy git:(master) ✗ ./gk-deploy -g
Welcome to the deployment tool for GlusterFS on Kubernetes and OpenShift.

Before getting started, this script has some requirements of the execution
environment and of the container platform that you should verify.

The client machine that will run this script must have:
 * Administrative access to an existing Kubernetes or OpenShift cluster
 * Access to a python interpreter 'python'
 * Access to the heketi client 'heketi-cli'

Each of the nodes that will host GlusterFS must also have appropriate firewall
rules for the required GlusterFS ports:
 * 2222  - sshd (if running GlusterFS in a pod)
 * 24007 - GlusterFS Daemon
 * 24008 - GlusterFS Management
 * 49152 to 49251 - Each brick for every volume on the host requires its own
   port. For every new brick, one new port will be used starting at 49152. We
   recommend a default range of 49152-49251 on each host, though you can adjust
   this to fit your needs.

In addition, for an OpenShift deployment you must:
 * Have 'cluster_admin' role on the administrative account doing the deployment
 * Add the 'default' and 'router' Service Accounts to the 'privileged' SCC
 * Add the 'heketi-service-account' Service Account to the 'privileged' SCC
 * Have a router deployed that is configured to allow apps to access services
   running in the cluster

Do you wish to proceed with deployment?

[Y]es, [N]o? [Default: Y]: y
CLI1:
CLI2:  /usr/local/bin/kubectl
Using OpenShift CLI.
CLI3:  /usr/local/bin/kubectl
```

I think the problem is the if statements:

```
if [[ "${CLI}" == *oc* ]]; then
  output "Using OpenShift CLI."
elif [[ "${CLI}" == *kubectl* ]]; then
  output "Using Kubernetes CLI."
else
  output "Unknown CLI '${CLI}'."
  exit 1
fi
```
If you look at my path to the kubectl binary:

/usr/l**oc**al/bin/kubectl

*oc* will trigger on this since it contains 'l**oc**al'

Removing the trailing * from both 'oc' & 'kubectl' makes it detect the kubectl cli for me.

Maybe this can be done better with a =~ regex that checks if the line ends in /oc or /kubectl?

Cheers!

**Comment by jarrpa** [comment]
HAH! Good catch!

I'm not sure a regexp is necessary here. We can't just check for strings ending in `/<CLI>` because we should still deal with the case where CLI doesn't include the full path. Does it seem like it could just be done by changing the globs to `*<CLI>`?

**Comment by roffe** [comment]
I would say that should be sufficient. I did not have any misshaps in my local dev environment when trying the modified globs.

Have a nice day!

**Comment by jarrpa** [comment]
Closing this issue, as it seems to have been resolved by #148. :)

**Comment by roffe** [comment]
Hi jarrpa

Sorry for not getting back to and leaving the issue hanging.

I've redeployed several times using the updated script and have had no problems so far :)
