### ISSUE TITLE
GlusterFS cant mount volume at container creation

### ISSUE THREAD

**Issue by felixPG** [gluster/gluster-kubernetes#334]
[nginx-pod-glusterfs.log.txt](https://github.com/gluster/gluster-kubernetes/files/1266807/nginx-pod-glusterfs.log.txt)
Hi:

I habe a glusterfs running inside kubernetes, PV and PVC created withour problems but pods are unable to mount the volumes that  I want:

Here my config files:

StorageClass and Claim:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://s-smartc2-zprei:30625"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster1
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 1Gi
```
Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: gcr.io/google_containers/nginx-slim:0.8
    ports:
    - name: web
      containerPort: 80
    securityContext:
      privileged: true
    volumeMounts:
    - name: gluster-vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: gluster-vol1
    persistentVolumeClaim:
      claimName: gluster1
```

Pods are in ContainerCreating status forever, here the logs of the pod:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pods
NAME                     READY     STATUS              RESTARTS   AGE
glusterfs-72rcn          1/1       Running             0          1h
glusterfs-hfvrd          1/1       Running             1          1h
glusterfs-msqlp          1/1       Running             0          1h
heketi-730120522-d36p6   1/1       Running             0          1h
nginx-pod                0/1       ContainerCreating   0          4m
```
Pod Logs:
```
  3m    3m      1       kubelet, s-smartc4-zprei                **Warning FailedMount**     MountVolume.SetUp failed for volume "pvc-89998771-8e37-11e7-9fa1-005056b77c78" : glusterfs: mount failed: mount failed: exit status 1
Mounting command: mount
Mounting arguments: 192.168.133.4:**vol_cd634264e40aa5a24bc21d8b73c3c787** /var/lib/kubelet/pods/9985b31a-8e37-11e7-9fa1-005056b77c78/volumes/kubernetes.io~glusterfs/pvc-89998771-8e37-11e7-9fa1-005056b77c78 glusterfs [auto_unmount log-level=ERROR log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-89998771-8e37-11e7-9fa1-005056b77c78/nginx-pod-glusterfs.log backup-volfile-servers=192.168.133.2:192.168.133.3:192.168.133.4]
**Output: /usr/bin/fusermount-glusterfs: mount failed: Invalid argument**
Mount failed. Please check the log file for more details.

 the following error information was pulled from the glusterfs log to help diagnose this issue:
[2017-08-31 10:34:00.548499] I [client.c:2294:notify] 0-vol_cd634264e40aa5a24bc21d8b73c3c787-client-0: parent translators are ready, attempting connect on transport
[2017-08-31 10:34:00.550338] I [client.c:2294:notify] 0-vol_cd634264e40aa5a24bc21d8b73c3c787-client-1: parent translators are ready, attempting connect on transport
```

PV and PVC details:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM              STORAGECLASS     REASON    AGE
pvc-89998771-8e37-11e7-9fa1-005056b77c78   1Gi        RWO           Delete          **Bound**     default/gluster1   gluster-heketi             6m
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pvc
NAME       STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS     AGE
gluster1   **Bound**     pvc-89998771-8e37-11e7-9fa1-005056b77c78   1Gi        RWO           gluster-heketi   6m
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Glusterfs connectivity test:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# curl s-smartc2-zprei:30625/hello
Hello from Heketiroot@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Volume info FROM glusterfs pod:
```
[root@s-smartc4-zprei /]# gluster volume info vol_cd634264e40aa5a24bc21d8b73c3c787

Volume Name: vol_cd634264e40aa5a24bc21d8b73c3c787
Type: Replicate
Volume ID: f895aa2d-d60c-4343-ad9a-b7a2a9bd1934
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 192.168.133.4:/var/lib/heketi/mounts/vg_acdc18362c9aa66cdcbf400c59c2cea1/brick_f4a87ef6fdd1cb0af420dff3da64a213/brick
Brick2: 192.168.133.3:/var/lib/heketi/mounts/vg_c7217dce005502fd5a2bc9eb775809b8/brick_15bdd5f4baa6aac305b92dea8a47d5e4/brick
Brick3: 192.168.133.2:/var/lib/heketi/mounts/vg_4c0de25e23a85bb1c2d47c5883be84db/brick_6e9e7dfdcd25a24618efe62193b0eb26/brick
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
```
Node Pod provisioned:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl describe pod nginx-pod |grep Node
Node:           s-smartc4-zprei/192.168.133.4
Node-Selectors: <none>
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Attached the log from the node where the pod was provisioned.

Could anyone sayme waht happend with the moun command???? 

Thanks

**Comment by felixPG** [comment]
Searching and searching I found a post with a possible explain of the problem: 

https://github.com/kubernetes/kubernetes/issues/50463

Appear to be the glusterfs version, in ma case:

[root@s-smartc4-zprei /]# glusterfs --version
**glusterfs 3.10.2**
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
[root@s-smartc4-zprei /]#

But Im using the image: gluster/gluster-centos:latest because an issue open by me about node add to glusterfs:
https://github.com/gluster/gluster-kubernetes/issues/328

So, the version of glusterfs in image gluster/gluster-centos:latest is 3.10.2 but DOES NOT WORK with the parameters of mount command, need version at least 3.11.1, please, what IMAGE I could use to resolve this problem?????

**Comment by jarrpa** [comment]
@felixPG The Kube issue you linked seems to indicate that it should remount without the invalid version... Can you try to see if you can mount the volume somewhere on the node running the nginx pod, like:
```
mount -t glusterfs -o default_permissions,auto_unmount,allow_other,max_read=131072 192.168.133.3:vol_cd634264e40aa5a24bc21d8b73c3c787 /mnt
```

We currently do not have an upstream image running GlusterFS 3.11. This may be coming in short order, but for now we'll have to try and make do with 3.10.

P.S. Please use `` ``` `` to encapsulate any terminal/log output you paste into a comment. :)

**Comment by felixPG** [comment]
@jarrpa  recreated the scenario with your mount command:

***
root@s-smartc4-zprei:~# mount -t glusterfs -o default_permissions,auto_unmount,allow_other,max_read=131072 192.168.133.3:vol_25118315f5003699df8c2e589af2a62a /opt/testglusterfs
/usr/bin/fusermount-glusterfs: mount failed: Invalid argument
Mount failed. Please check the log file for more details.

***
Logs FROM node:

***

[2017-09-01 11:01:26.319631] I [glusterfsd.c:1959:main] 0-/usr/sbin/glusterfs: Started running /usr/sbin/gl            usterfs version 3.5.2 (/usr/sbin/glusterfs --fuse-mountopts=default_permissions,auto_unmount,allow_other,ma            x_read=131072 --volfile-server=192.168.133.3 --volfile-id=vol_25118315f5003699df8c2e589af2a62a --fuse-mount            opts=default_permissions,auto_unmount,allow_other,max_read=131072 /opt/testglusterfs)
[2017-09-01 11:01:26.320467] I [mount.c:290:gf_fuse_mount] 0-glusterfs-fuse: direct mount failed (Invalid a            rgument), retry to mount via fusermount
[2017-09-01 11:01:26.321456] I [socket.c:3578:socket_init] 0-glusterfs: SSL support is NOT enabled
[2017-09-01 11:01:26.321489] I [socket.c:3593:socket_init] 0-glusterfs: using system polling thread
[2017-09-01 11:01:26.322976] E [mount.c:298:gf_fuse_mount] 0-glusterfs-fuse: mount of 192.168.133.3:vol_251            18315f5003699df8c2e589af2a62a to /opt/testglusterfs (default_permissions,default_permissions,auto_unmount,a            llow_other,max_read=131072,allow_other,max_read=131072) failed
[2017-09-01 11:01:26.323449] E [glusterfsd.c:1793:daemonize] 0-daemonize: mount failed
[2017-09-01 11:01:26.325450] I [dht-shared.c:311:dht_init_regex] 0-vol_25118315f5003699df8c2e589af2a62a-dht            : using regex rsync-hash-regex = ^\.(.+)\.[^.]+$
[2017-09-01 11:01:26.326875] I [socket.c:3578:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-2:             SSL support is NOT enabled
[2017-09-01 11:01:26.326899] I [socket.c:3593:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-2:             using system polling thread
[2017-09-01 11:01:26.327235] I [socket.c:3578:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-1:             SSL support is NOT enabled
[2017-09-01 11:01:26.327261] I [socket.c:3593:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-1:             using system polling thread
[2017-09-01 11:01:26.327552] I [socket.c:3578:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-0:             SSL support is NOT enabled
[2017-09-01 11:01:26.327581] I [socket.c:3593:socket_init] 0-vol_25118315f5003699df8c2e589af2a62a-client-0:             using system polling thread
[2017-09-01 11:01:26.327598] W [graph.c:329:_log_if_unknown_option] 0-vol_25118315f5003699df8c2e589af2a62a-            readdir-ahead: option 'parallel-readdir' is not recognized
[2017-09-01 11:01:26.327610] W [graph.c:329:_log_if_unknown_option] 0-vol_25118315f5003699df8c2e589af2a62a-            readdir-ahead: option 'rda-cache-limit' is not recognized
[2017-09-01 11:01:26.327628] W [graph.c:329:_log_if_unknown_option] 0-vol_25118315f5003699df8c2e589af2a62a-            dht: option 'lock-migration' is not recognized
[2017-09-01 11:01:26.327638] W [graph.c:329:_log_if_unknown_option] 0-vol_25118315f5003699df8c2e589af2a62a-            replicate-0: option 'afr-pending-xattr' is not recognized
[2017-09-01 11:01:26.327651] W [graph.c:329:_log_if_unknown_option] 0-vol_25118315f5003699df8c2e589af2a62a-            replicate-0: option 'use-compound-fops' is not recognized
[2017-09-01 11:01:26.327704] I [client.c:2294:notify] 0-vol_25118315f5003699df8c2e589af2a62a-client-0: pare            nt translators are ready, attempting connect on transport
[2017-09-01 11:01:26.328171] I [client.c:2294:notify] 0-vol_25118315f5003699df8c2e589af2a62a-client-1: pare            nt translators are ready, attempting connect on transport
[2017-09-01 11:01:26.328483] I [client.c:2294:notify] 0-vol_25118315f5003699df8c2e589af2a62a-client-2: pare            nt translators are ready, attempting connect on transport

***

**Comment by felixPG** [comment]
Only for confirm, the problem is with **auto_unmount** parameter:

***
root@s-smartc4-zprei:~# mount -t glusterfs -o auto_unmount,allow_other,max_read=131072 192.168.133.3:vol_25118315f5003699df8c2e589af2a62a /opt/testglusterfs
/usr/bin/fusermount-glusterfs: mount failed: Invalid argument
Mount failed. Please check the log file for more details.
root@s-smartc4-zprei:~#
root@s-smartc4-zprei:~# mount -t glusterfs -o default_permissions,allow_other,max_read=131072 192.168.133.3:vol_25118315f5003699df8c2e589af2a62a /opt/testglusterfs
root@s-smartc4-zprei:~# df -h |grep test
192.168.133.3:vol_25118315f5003699df8c2e589af2a62a  1014M    33M  982M   4% /opt/testglusterfs
root@s-smartc4-zprei:~#

***

**Comment by jarrpa** [comment]
@felixPG Why yes, you can test it out for yourself! :) Our repo includes a vagrant environment that will spin up a VM Kubernetes cluster on your local machine and can run gk-deploy to deploy GlusterFS on said Kube cluster. It uses Kube 1.6.1 with the latest version of the gluster-centos image. The particular commit you linked is ONLY in Kube >=1.7.0. As of Kube 1.7.3 [this PR](https://github.com/kubernetes/kubernetes/pull/48709) has been merged, which I imagine should fix the problem.

**Comment by felixPG** [comment]
Thanks for you reply @jarrpa .Im use 1.7.4 and the problem persist.

**Comment by felixPG** [comment]
Please, any update for this???

**Comment by jarrpa** [comment]
Sorry, you left your second-to-latest comment at midnight my time, and today was a holiday. :)

Unfortunately, I have no direct control over the builds for the gluster/gluster-centos image. :( My suggestion would be that you should reply to https://github.com/kubernetes/kubernetes/issues/50463 on the Kubernetes GitHub, since this is fundamentally a Kube problem. Mention the following PRs and that they don't seem to have solved your problem in 1.7.4:

* https://github.com/kubernetes/kubernetes/pull/45995
* https://github.com/kubernetes/kubernetes/pull/46614

**Comment by felixPG** [comment]
Thanks so much @jarrpa , I will open a issue to k8s. I will back with a reply of k8s maintainers.

**Comment by grebois** [comment]
@jarrpa having the same issue with glusterfs 3.12;

```
$ kubectl exec -it -n kube-system glusterfs-3sgkq bash
[root@int00web12 /]# glusterfs --version
glusterfs 3.12.0
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
[root@int00web12 /]#
```

and kube 1.7.5;

```
$ kubectl get nodes
NAME         STATUS    AGE       VERSION
int00web10   Ready     4d        v1.7.5+coreos.0
int00web11   Ready     4d        v1.7.5+coreos.0
int00web12   Ready     4d        v1.7.5+coreos.0
```

Output;

```
PersistentVolumeClaim is not bound: "mysql-pv-claim" (repeated 3 times)
MountVolume.SetUp failed for volume "pvc-ec5521e2-9804-11e7-b0ee-0cc47a3079e8" : glusterfs: mount failed: mount failed: exit status 1 Mounting command: mount Mounting arguments: 10.105.144.79:vol_6e0be4bb24b40b75e6e2daa2244104fd /var/lib/kubelet/pods/ec6729af-9804-11e7-9b9b-0cc47a3070e0/volumes/kubernetes.io~glusterfs/pvc-ec5521e2-9804-11e7-b0ee-0cc47a3079e8 glusterfs [log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-ec5521e2-9804-11e7-b0ee-0cc47a3079e8/wordpress-mysql-918363043-w2zm8-glusterfs.log backup-volfile-servers=10.105.144.101:10.105.144.69:10.105.144.79 auto_unmount log-level=ERROR] Output: /usr/bin/fusermount-glusterfs: mount failed: Invalid argument Mount failed. Please check the log file for more details. the following error information was pulled from the glusterfs log to help diagnose this issue: [2017-09-12 21:54:24.530406] E [glusterfsd.c:1793:daemonize] 0-daemonize: mount failed [2017-09-12 21:54:24.533310] I [dht-shared.c:311:dht_init_regex] 0-vol_6e0be4bb24b40b75e6e2daa2244104fd-dht: using regex rsync-hash-regex = ^\.(.+)\.[^.]+$

Mounting arguments: 10.105.144.79:vol_75d5f19520a0ae0a1e08879c5118b2dc /var/lib/kubelet/pods/46240ee5-97fd-11e7-9dd4-0cc47a3070e0/volumes/kubernetes.io~glusterfs/pvc-460f9c1c-97fd-11e7-9301-0cc47a3079e8 glusterfs [auto_unmount log-level=ERROR log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-460f9c1c-97fd-11e7-9301-0cc47a3079e8/wordpress-mysql-918363043-qcf0b-glusterfs.log backup-volfile-servers=10.105.144.101:10.105.144.69:10.105.144.79]
Output: /usr/bin/fusermount-glusterfs: mount failed: Invalid argument
Mount failed. Please check the log file for more details.
```

**Comment by jarrpa** [comment]
@grebois Please continue the conversation on the Kubernetes GitHub. I'm keeping the Issue open until the broader problem is resolved, but there's nothing we can immediately do on our end.

**Comment by grebois** [comment]
@jarrpa sure, will do, sorry.

**Comment by clementnero** [comment]
Any workaround with kube 1.7.5 and gluster 3.10.2 ?

**Comment by jarrpa** [comment]
@clementnero Not at this time. :(

**Comment by clementnero** [comment]
@jarrpa no problem, for now I have built my own release of Kubernetes applying this [PR](https://github.com/kubernetes/kubernetes/pull/52365), [cnero/hyperkube-amd64:v1.7.5-PR52365](https://hub.docker.com/r/cnero/hyperkube-amd64/tags/)

**Comment by humblec** [comment]
@clementnero We are close and we will have a fix soon.

**Comment by clementnero** [comment]
Fixed in 1.8, thx for your work.

**Comment by jarrpa** [comment]
@clementnero Woo!

@felixPG Can you see if the issue is resolved with the latest k8s?

**Comment by felixPG** [comment]
@jarrpa I cant upgrade now to the latest k8s, when problems arrive with glusterfs I create an NFS and is working like a charm; when I have a time I will make a test on small cluster. Thanks for your reply.

**Comment by humblec** [comment]
Yes, this is fixed in 1.8. \o/

**Comment by jarrpa** [comment]
@felixPG All right, I won't hold you to anything if you think it'll be a hassle. :) Closing this Issue. If you later find that the problem is not resolved we can reopen this.
